#!/usr/bin/env sh

rofm="rofi -dmenu -i -config ~/.config/rofi/menu.rasi"
dmem="dmenu -i"
wofm="wofi -dib -W 60% -H 55% -w 2"
bmem="bemenu"
menu=$bmem

a1=" Insert Emoji/Icons"
a2=" Dictionary"
a3=" Set Reminder"
a4="⏲ Time & Date Now"
a5=" System Stats"
a6=" YouTube"
a7="🗒 TODO"
a8=" Music"
a9=" Pirate Mode"

chosen=$(printf "$a1\n$a2\n$a3\n$a4\n$a5\n$a6\n$a7\n$a8\n$a9" | $menu -p 'sapps')

case "$chosen" in
        "$a1") d-unicodes ;;
        "$a2") d-dict ;;
        "$a3") d-remind ;;
        "$a4") d-time ;;
        "$a5") d-stats ;;
        "$a6") ytfzf -D ;;
        "$a7") d-todo ;;
        "$a8") d-mpd ;;
        "$a9") d-pirt ;;
	*) exit 1 ;;
esac
