#!/usr/bin/env sh
rmem="rofi -dmenu -i -config ~/.config/rofi/menu.rasi"
dmem="dmenu -i"
bmem="bemenu"
menu=$bmem

# edit it your cheatsheet and add below
getkeys() {
         bat ~/.config/dk/sxhkdrc | awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' | column -t -s $'\t' | dmenu -i -l 20 -p "Key Bindings:" 
     }

a1=" Powermenu"
a2=" Change Wallpaper"
a3=" Handle Stuffs"
a4=" Music Menu"
a5=" Mini Apps"

chosen=$(printf "$a1\n$a2\n$a3\n$a4\n$a5" | $menu)

case "$chosen" in
        "$a1") d-power ;;
        "$a2") d-walls ;;
        "$a3") d-stuff ;;
        "$a5") d-apps ;;
        "$a4") d-mpdplay ;;
	*) exit 1 ;;
esac
