#!/usr/bin/env zsh

# Simple script which show the bookmarks from org-file which are inserted via d-bookmark

# We can select and it insert the link

wtype "$(rg -v '^$' ~/sync/org/bookmarks.org | bemenu -W 0.8  | rg -o '(http|https)://[a-zA-Z0-9./?=_%:-]*')"
