#!/usr/bin/env zsh

# Simple script which show the bookmarks from org-file which are inserted via d-bookmark

# We can select and it insert the link

rofm="rofi -dmenu"
mymem=$rofm



wtype "$(rg -v '^$' ~/sync/org/bookmarks.org | ${mymem}  | rg -o '(http|https)://[a-zA-Z0-9./?=_%:-]*')"
