#!/usr/bin/env sh
pidof -x mpd || mpd &
rofm="rofi -dmenu -config ~/.config/rofi/menu.rasi "
dmem="dmenu"
bmem="bemenu"
menu=$bmem

a1="  Queued Song"
a2="🎹 Advance Menu"
# FOR $menu
chosen=$(printf "$a2\n Pause\n Seek +10\n Random Song\n Seek -10 Back\n Next Track\n Prev Track\n Play\n Stop Music\n Choose Song\n$a1" | sort | $menu -i -l 12 -p '   MPD Menu ')

case "$chosen" in
" Play") mpc play ;;
" Pause") mpc pause ;;
" Next Track") mpc next ;;
" Prev Track") mpc prev ;;
" Random Song") mpc random ;;
" Seek +10") mpc seek +10% ;;
" Seek -10 Back") mpc seek -10% ;;
" Stop Music")
	mpc stop &
	pkill mpd
	;;
" Choose Song") mpc update && d-mpd ;;
"$a1") notify-send "Next song in Queue" "$(mpc queued)" ;;
"$a2") d-mpdm ;;
*) exit 1 ;;
esac
